const PDFDocument = require('pdfkit');
const Score = require('../models/Score');
const { getWeakTopics } = require('./weakTopics.service');

// ── Report service ───────────────────────────────────────────
// v1.4.1. Streams a one-page PDF performance summary for a single
// student — used by the admin dashboard's "Download PDF report"
// action. Built directly with pdfkit (no headless browser/HTML-to-PDF
// step), so it's cheap enough to run on PrepHQ's free-tier hosting.

function drawSectionTitle(doc, text) {
  doc.moveDown(0.6);
  doc.fontSize(13).fillColor('#0A5CF5').font('Helvetica-Bold').text(text);
  doc.moveDown(0.2);
  doc.fillColor('#000000').font('Helvetica');
}

async function generatePerformanceReportPDF(student, res) {
  const scores = await Score.find({ matric: student.matric }).sort({ ts: -1 }).limit(50).lean();
  const weakTopics = await getWeakTopics(student.matric, 5);

  const avgPct = scores.length ? Math.round(scores.reduce((a, s) => a + s.pct, 0) / scores.length) : null;
  const bestPct = scores.length ? Math.max(...scores.map(s => s.pct)) : null;
  const totalQuizzes = scores.length;

  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${student.matric}-performance-report.pdf"`);
  doc.pipe(res);

  // ── Header ──
  doc.fontSize(20).font('Helvetica-Bold').fillColor('#0A5CF5').text('PrepHQ Performance Report');
  doc.moveDown(0.2);
  doc.fontSize(10).font('Helvetica').fillColor('#555555').text(`Generated ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`);
  doc.moveDown(1);

  // ── Student info ──
  doc.fontSize(14).font('Helvetica-Bold').fillColor('#000000').text(student.name);
  doc.fontSize(10).font('Helvetica').fillColor('#555555')
    .text(`Matric: ${student.matric}   |   University: ${student.university || 'Not set'}   |   Department: ${student.department || 'Not set'}`);
  doc.text(`Plan: ${student.tier.charAt(0).toUpperCase() + student.tier.slice(1)}`);

  // ── GPA ──
  drawSectionTitle(doc, 'GPA Progress');
  doc.text(`Current GPA: ${student.currentGPA ?? 'Not set'}   |   Target GPA: ${student.targetGPA ?? 'Not set'}   |   Scale: 0–${student.gpaScale}`);

  // ── Quiz performance overview ──
  drawSectionTitle(doc, 'Quiz Performance (last 50 quizzes)');
  doc.text(`Quizzes taken: ${totalQuizzes}`);
  doc.text(`Average score: ${avgPct != null ? avgPct + '%' : 'No data yet'}`);
  doc.text(`Best score: ${bestPct != null ? bestPct + '%' : 'No data yet'}`);

  // ── Recent quiz history table (simple line-per-row) ──
  if (scores.length) {
    drawSectionTitle(doc, 'Recent Quiz History');
    scores.slice(0, 10).forEach(s => {
      const date = new Date(s.ts).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' });
      doc.fontSize(9.5).text(`${date}   ${s.courses || 'Mixed'}   —   ${s.pct}% (${s.correct}/${s.total})`);
    });
  }

  // ── Weak topics ──
  drawSectionTitle(doc, 'Topics Needing Attention');
  if (weakTopics.length) {
    weakTopics.forEach(t => {
      doc.fontSize(9.5).text(`${t.course} — ${t.tag}: ${t.accuracy}% accuracy over last ${t.attempts} attempts`);
    });
  } else {
    doc.fontSize(9.5).fillColor('#777777').text('Not enough recent tagged-question data yet to identify weak topics.');
  }

  doc.moveDown(2);
  doc.fontSize(8).fillColor('#999999').text('Generated by PrepHQ — this report reflects data at the time of generation.');

  doc.end();
}

module.exports = { generatePerformanceReportPDF };
